services:
  simple-lb:
    build: .
    ports:
      - "80:80"          # HTTP traffic
      - "443:443"        # HTTPS traffic
      - "81:81"          # Management web interface (HTTPS)
      - "2019:2019"      # Caddy Admin API
    environment:
      # Management Interface Authentication
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - MANAGEMENT_PORT=81
      
      # Security Configuration
      - SESSION_SECRET=your-super-secret-session-key-change-this-in-production
      - SESSION_COOKIE_SECURE=0       # Set to 1 for HTTPS in production
      
      # Rate Limiting Configuration (requests per minute)
      - GENERAL_RATE_LIMIT=60         # All endpoints (60/min)
      
      # SSL/TLS Configuration
      - ACME_EMAIL=admin@example.com  # Email for Let's Encrypt certificates
      
      # Caddy Integration
      - CADDY_ADMIN_URL=http://127.0.0.1:2019  # Caddy Admin API URL
    volumes:
      - ./data:/app/data
    restart: unless-stopped